name: weather_forecasts
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: UbuntuCondensed
      fonts:
        - asset: assets/fonts/UbuntuCondensed-Regular.ttf
  uses-material-design: true
